### PR TITLE
ATA-1837 Make kbuckets and node records public in krouter.

### PR DESCRIPTION
**Pull request by jtownson**

### CODE REVIEW

**Review by KonradStaniec — APPROVED** [review]

**Review by krcz — APPROVED** [review]
Looks good to me

**Comment by loverdos** [comment]
I cannot even compile this, am I missing something?

```sh
$ mill-0.4.1  __.test
[31/110] scalanet.compile 
[info] Compiling 24 Scala sources to /scalanet/out/scalanet/compile/dest/classes ...
[error] /scalanet/scalanet/src/io/iohk/scalanet/peergroup/kademlia/BitVectorCodec.scala:3:8: object CodecContract is not a member of package io.iohk.decco
[error] import io.iohk.decco.CodecContract
[error]        ^
[error] /scalanet/scalanet/src/io/iohk/scalanet/peergroup/kademlia/BitVectorCodec.scala:9:72: not found: type CodecContract
[error]   implicit def bitVectorInstance(implicit iCodec: CodecContract[Int]): CodecContract[BitVector] =
[error]                                                                        ^
[error] /scalanet/scalanet/src/io/iohk/scalanet/peergroup/kademlia/BitVectorCodec.scala:9:51: not found: type CodecContract
[error]   implicit def bitVectorInstance(implicit iCodec: CodecContract[Int]): CodecContract[BitVector] =
[error]                                                   ^
[error] /scalanet/scalanet/src/io/iohk/scalanet/peergroup/kademlia/BitVectorCodec.scala:10:51: missing parameter type
[error]     ByteArrayCodec.map(array => BitVector(array), bitVector => bitVector.toByteArray)
[error]                                                   ^
[error] /scalanet/scalanet/src/io/iohk/scalanet/peergroup/kademlia/BitVectorCodec.scala:3:22: Unused import
[error] import io.iohk.decco.CodecContract
[error]                      ^
[error] 5 errors found
1 targets failed
scalanet.compile Compilation failed
```

**Comment by loverdos** [comment]
So it was the usual problem of depending on a SNAPSHOT, I had to clear local ivy files. Thanks to Shailesh for the suggestion.

**Review by loverdos — CHANGES_REQUESTED** [review]
We need to depend on non-SNAPSHOT versions of decco etc.

**Comment by mineme0110** [comment]
> We need to depend on non-SNAPSHOT versions of decco etc.

https://repo1.maven.org/maven2/io/iohk/decco-auto_2.12/
decco 0.2 version is released now

**Review by loverdos — APPROVED** [review]
Thanks!

**Pull request merged**
