### PR TITLE
Release/0.7.0

### PR DESCRIPTION
**Pull request by KonradStaniec**
# Description

Release version 0.7.0

# Features added since 0.6.0

#124 - add new validations from libp2p specs
#126 - add option to throttle incoming connections from the same ip
#127 - force tls1.3 on tls connections
#128 - use netty native framing codecs instead of homegrown ones
#129 - discerns peers in different networks on discovery level
#130 - add basic back pressoure for incoming messages by using netty auto read feature

### CODE REVIEW

**Review by aakoshh — APPROVED** [review]
:+1:

**Comment by aakoshh** [comment]
Maybe we should have a CHANGELOG, or just list what was added in these PRs.

**Comment by KonradStaniec** [comment]
good point! for now I have added list of changes and pr-s merged since last release. I will add change log in next release iteration

**Comment by aakoshh** [comment]
That list is perfect, thanks!

**Pull request merged**
